### ISSUE TITLE
POM file for a PHP project

### ISSUE THREAD

**Issue by bozhidarc** [mibexsoftware/sonar-bitbucket-plugin#18]
Hi,

I want to use the sonar bitbucket plugin for analyzing a PHP project.
I'm not very familiar with Maven but when Jenkins run mvn command with the supplied arguments it complains for POM file.

_"The goal you specified requires a project to execute but there is no POM in this directory"_

I read the POM basics from [Maven](https://maven.apache.org/pom.html#The_Basics) website but I'm not sure what to set for "packaging" when I don't package my project.

Can you give me a hint how to run sonar for PHP project?

**Comment by mrueegg** [comment]
Hi,

For a PHP project I would recommend that you use SonarRunner to trigger the analysis because Maven is better suited for Java projects where you make use of Maven for building the project anyway.

Please see this sample project on how you can configure SonarRunner for your PHP build: https://github.com/SonarSource/sonar-examples/tree/master/projects/languages/php/php-sonar-runner

You can then trigger the Sonar analysis (and this plug-in) like this:

`
sonar-runner -Dsonar.analysis.mode=issues <other-options>
`

Hope this helps.

Cheers,
Michael
