### ISSUE TITLE
Adding comments on every maven build

### ISSUE THREAD

**Issue by lopesdasilva** [mibexsoftware/sonar-bitbucket-plugin#33]
Hi, I've been trying to use your plugin.
I'm seeing that every time I run the maven build the same comments are being added.
I'm also seeing that no issues are being found on the  pull request, but if I go to the sonar and open those class files, they have issue. Are this only analyzing the new/modified lines?

Thanks

**Comment by mrueegg** [comment]
Hi,

Exactly, we only create issues on new/modified code lines. This is because we do not want to overwhelm and distract pull request reviewers with a huge amount of issues, but instead let them focus on issues in the diff of the pull request.

**Comment by lopesdasilva** [comment]
Could this be a setting? 
And what about the question regarding the multiple comments on every build?

**Comment by mrueegg** [comment]
Yes, this could be a setting. Could you please create a separate feature request for it?

Regarding your question about creating the same comments every time: the plug-in checks if the same issue has already been reported and in that case doesn't delete and re-create a comment for it. Issues not reported anymore get deleted, and for new issues we create new comments. Have you experienced a different behavior?

**Comment by lopesdasilva** [comment]
Hi, 
I'm getting multiple message when there's no issue found. (PFA)
![image](https://cloud.githubusercontent.com/assets/1013126/20519710/e138eb84-b09b-11e6-8cc7-567116e74285.png)
Thanks for you support

**Comment by imunic** [comment]
You are using oauth right, and the same account isn't the owner of the repo? It happen's because of:

https://github.com/mibexsoftware/sonar-bitbucket-plugin/blob/master/src/main/scala/ch/mibex/bitbucket/sonar/client/BitbucketClient.scala#L103

If you aren't using the repo owner account it can't match the existing comments with the logged in user (this is the same as issue #22)

I fixed it by modifying the code to call the 2.0 API "user" endpoint after login and storing the logged in users uuid, and changed the comments fetch operation to use the 2.0 API.

@mrueegg I'm no scala expert so my code probably isn't "on par", but if you wan't I can create a PR for you to look at

**Comment by mrueegg** [comment]
@imunic Thanks for your feedback. A pull request would be much appreciated :-) I'm happy to review it.

**Comment by mrueegg** [comment]
Fixed with release [1.1.7](https://github.com/mibexsoftware/sonar-bitbucket-plugin/releases/tag/v1.1.7) thanks to the contribution of @imunic
